### ISSUE TITLE
Refactor globals into a PlayerState table

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/WorldEdit#17]
There are too many globals that keep track of the various aspect of player state:
`OnePlayer`, `TwoPlayer`, `PersonalUndo`, `PersonalRedo`, `LastCoords`, `LastRedoCoords` and possibly more.

These should all be refactored into a single player state table:
```lua
local State = GetPlayerState(a_Player:GetUniqueID())
State.Selection:SetFirstPoint(50, 50, 50)
State.Selection:SetSecondPoint(70, 70, 70)
State:PushUndo(SomeBlockArea)
-- etc.
```

**Comment by NiLSPACE** [comment]
I think this can now be closed?

**Comment by NiLSPACE** [comment]
I'm closing this.
