### ISSUE TITLE
Add a "cBlockTypeSource" (interface) class

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/WorldEdit#49]
This interface would provide individual blocktypes for the various `set`, `walls`, `replace` and other such operations - they will ask the class to provide a blocktype for each block they set, and the class implementation will decide what blocktype to return.
Then, we can make multiple descendants that implement various behaviors:
- `cConstantBlockTypeSource` returns the same blocktype for each query. Used for regular `set` operations.
- `cRandomBlockTypeSource` returns a weighted-random blocktype for each query. Used for percent-based `set` operations.
- `cClipboardBlockTypeSource` returns a blocktype based on the clipboard, in a repeating pattern. See http://wiki.sk89q.com/wiki/WorldEdit/Block_data_syntax#Clipboard for details

**Comment by NiLSPACE** [comment]
I don't think we need `cConstantBlockTypeSource`, since almost every operation can use multiple block's.

**Comment by madmaxoft** [comment]
Yes, the `cConstantBlockTypeSource` is technically a subset of `cRandomBlockTypeSource`. Still, separating it might give a slight perf boost.

**Comment by NiLSPACE** [comment]
I'm lost, where would `cConstantBlockTypeSource` be used, and how would it be different from `cRandomBlockTypeSource`.

**Comment by madmaxoft** [comment]
`cConstantBlockTypeSource` is used when a single block type is to be used for the entire operation: `/fill stone`

`cRandomBlockTypeSource` would be used when multiple block types are given for the operation:
`/fill stone,dirt,gravel` (not sure what the exact syntax is)

**Comment by NiLSPACE** [comment]
That makes sense. Then we should have a function that chooses the best `cBlockTypeSource`.

I don't think the `Get` functions would need the coordinates as a parameter though.

**Comment by madmaxoft** [comment]
It does, for the `cClipboardBlockTypeSource`. How else would you know which of the clipboard blocks to return?

**Comment by NiLSPACE** [comment]
Oh, is that how the clipboard worked? I thought it would randomly pick a block that is in the clipboard.

If that's what the clipboard does, then what would happen we you try to set a selection that is bigger then your clipboard?
