### ISSUE TITLE
Move each command handler to a file according to the commands category.

### ISSUE THREAD

**Issue by NiLSPACE** [mc-server/WorldEdit#64]
I think we should move each of the command handler according to their category.
For example `cmd_Terraforming.lua` or `cmd_Clipboard.lua`

**Comment by madmaxoft** [comment]
I'd prefer files without the `cmd` prefix, because that messes up my normal workflow - I work with TotalCmd and quite often I need the command prompt, so I just type "cmd"; when there are files with a "cmd" prefix, TotalCmd tries to complete the filename instead of launching a command prompt :(

**Comment by NiLSPACE** [comment]
How about `command_X`? I do like the idea to have a prefix before the files. It makes all the command handler files group up a little.

**Comment by madmaxoft** [comment]
That feels too long. I guess the `cmd` prefix is alright, I'll learn to work around it.

**Comment by NiLSPACE** [comment]
Maybe `ch`? from CommandHandler.

**Comment by madmaxoft** [comment]
Not descriptive enough.

**Comment by NiLSPACE** [comment]
![Agreed](http://www.reactiongifs.us/wp-content/uploads/2014/06/agreed_pirates_caribbean.gif)

**Comment by NiLSPACE** [comment]
I'll get to this issue when I finish the `//generate` command.

**Comment by NiLSPACE** [comment]
Another option would be to not have any prefix, and move the files in a different folder. Then initialize all the files in the `main.lua` file.

**Comment by madmaxoft** [comment]
That might actually be the best course of action. I'm considering cleaning up the plugin logic quite a bit, too, by letting MCS load only a single fixed-name file and having that file `require` all other plugin files, so this is a somewhat related change.

**Comment by NiLSPACE** [comment]
Hmmm.. that would probably break 99% of all the plugins though.

**Comment by DevToaster** [comment]
Even if it does break almost every other plugin, it should be a super easy fix though.  Just rename the main file "main.lua" or whatever and require "blahutilityscript.lua"  It also lets you know what plugins are still being actively developed I guess.  Or perhaps have a config.ini that allows the plugin to determine if it wants that to happen, or stuff it into the Info.lua maybe?

**Comment by NiLSPACE** [comment]
That means that I'd have around 30 plugins to update :/

**Comment by NiLSPACE** [comment]
But lets talk about this somewhere else ;)
