### ISSUE TITLE
Don't allow schematics to be overwritten

### ISSUE THREAD

**Issue by mathias-github** [mc-server/WorldEdit#81]
As the title says, don't allow a schematic to be created if an identical name already exists. I'd love to see this feature added, as I run a server where all players get WorldEdit.

**Comment by NiLSPACE** [comment]
I'd probably have to implement a `//schematic delete` as well then. Shouldn't be too hard to do.

**Comment by NiLSPACE** [comment]
Bukkit's WorldEdit doesn't have this. I'll make it configurable :)

**Comment by NiLSPACE** [comment]
Could you try it now? You'll have to set Schematics.OverrideExistingFiles to false.

**Comment by NiLSPACE** [comment]
**bump**

**Comment by mathias-github** [comment]
It seems to work fine. Thanks!

**Comment by SphinxC0re** [comment]
No bumping! You could hurt him :smile:

**Comment by NiLSPACE** [comment]
I bump who I want, whenever I want *bumps myself*
